---
title: "vig1_user_guide"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vig1_user_guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7
)
```

```{r setup}
library(BayesRates)
library(dplyr)
library(ggplot2)
```

## Smoothing by across age

```{r}
divorce_2020 <- nz_divorces %>%
  filter(time == 2020) %>%
  select(-time)
popn_2020 <- nz_population %>%
  filter(time == 2020) %>%
  select(-time)

res_age <- smooth_age(nevent_df = divorce_2020,
                      py_df = popn_2020)
res_age
```

```{r}
components(res_age, what = "rates")
```

```{r}
components(res_age, what = "age_effect")
```


```{r}
rates_age_df <- augment(res_age)
head(rates_age_df)
```

```{r}
ggplot(rates_age_df, aes(x = age)) +
  facet_wrap(vars(sex)) +
  geom_pointrange(aes(ymin = .lower, y = .fitted, ymax = .upper)) +
  geom_point(aes(y = .observed), col = "blue")
```

## Smoothing across age and time


```{r}
res_agetime <- smooth_agetime(nevent_df = nz_divorces,
                              py_df = nz_population,
                              byvar = "sex")
res_agetime
```


```{r}
rates_agetime_df <- augment(res_agetime)
head(rates_agetime_df)
```

```{r, fig.height = 7}
ggplot(rates_agetime_df, aes(x = time)) +
  facet_wrap(vars(age)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper, fill = sex),
              alpha = 0.6) +
  geom_line(aes(y = .fitted, color = sex)) +
  geom_point(aes(y = .observed, color = sex),
             size = 0.25)
```


```{r}
age_effect <- components(res_agetime, what = "age_effect")
ggplot(age_effect, aes(x = age)) +
  facet_wrap(vars(sex)) +
  geom_pointrange(aes(ymin = .lower, y = .fitted, ymax = .upper))
```

```{r}
time_effect <- components(res_agetime, what = "time_effect") 
head(time_effect)
```

```{r, fig.height = 7}
ggplot(time_effect, aes(x = time, y = .fitted, color = sex)) +
  facet_wrap(vars(age)) +
  geom_line(aes(y = .fitted))
```

## Total rate

```{r}
res_cn <- smooth_agetime(nevent_df = cn_divorces,
                         py_df = cn_population,
                         spec_time = TimeFixed(),
                         byvar = "sex")
res_cn
```

```{r}
total_divorce_rate <- total_rate(res_cn)  
head(total_divorce_rate)
```

```{r}
ggplot(total_divorce_rate, 
       aes(x = time, y = .fitted, ymin = .lower, ymax = .upper)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(fill = "salmon") +
  geom_line() +
  geom_point(aes(y = .observed), col = "blue")
```



## Interpolation


```{r}
cn_divorces_5 <- cn_divorces %>%
  filter(time %in% seq(1980, 2020, 5))
res_cn5 <- smooth_agetime(nevent_df = cn_divorces_5,
                          py_df = cn_population,
                          spec_time = TimeFixed(),
                          byvar = "sex")
res_cn5
```

```{r}
rates_cn5 <- augment(res_cn5)
head(rates_cn5)
```


```{r, fig.height = 7}
rates_cn5_selected <- rates_cn5 %>%
  filter(age %in% seq(20, 50, 5),
         sex == "Female")
ggplot(rates_cn5_selected, 
       aes(x = time, y = .fitted, ymin = .lower, ymax = .upper)) +
  facet_wrap(vars(age)) +
  geom_ribbon(fill = "salmon") +
  geom_line() +
  geom_point(aes(y = .observed), col = "blue")
```
