---
title: "vig3_math"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vig3_math}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Model for single time period

\begin{equation}
  y_a \sim \text{Poisson}(\gamma_a w_a)
\end{equation}

\begin{equation}
  \log \gamma_a = \beta_a^{\text{age}}
\end{equation}

Priors for age effect $\beta_a^{\text{age}}$: 

Case 1: Second-Order Random Walk

\begin{equation}
  \beta_a^{\text{age}} - \beta_{a-1}^{\text{age}} \sim \text{N}\left(\beta_{a-1}^{\text{age}} - \beta_{a-2}^{\text{age}}, \sigma_{\text{age}}^2\right), \quad a = 2, \cdots, A
\end{equation}

where

\begin{equation}
  \sigma_{\text{age}} \sim \text{N}^+(0, s_{\text{age}}^2)
\end{equation}

Case 2: Spline

\begin{align}
  \pmb{\beta}^{\text{age}} & = \pmb{X} \pmb{\alpha} \\
  \alpha_a - \alpha_{a-1} & \sim \text{N}\left(\alpha_{a-1} - \alpha_{a-2}, \sigma_{\text{age}}^2\right)
\end{align}


where

\begin{equation}
  \sigma_{\text{age}} \sim \text{N}^+(0, s_{\text{age}}^2)
\end{equation}


# Model for multiple time periods: Main effects


\begin{align}
  y_{at} & \sim \text{Poisson}(\gamma_{at} w_{at}) \\
  \log \gamma_{at} & = \beta_a^{\text{age}} + \beta_t^{\text{time}}
\end{align}

Priors for age effect $\beta_a^{\text{age}}$ same as for single-time-period model

Prior for time effect:

\begin{equation}
  \beta_t^{\text{time}} \sim \text{N}(0, \sigma_{\text{time}}^2)
\end{equation}

# Model for multiple time periods: Interaction

\begin{align}
  y_{at} & \sim \text{Poisson}(\gamma_{at} w_{at}) \\
  \log \gamma_{at} & = \beta_a^{\text{age}} + \beta_{at}^{\text{age:time}}
\end{align}

Priors for age effect $\beta_a^{\text{age}}$ same as for single-time-period model

Prior for age-time effect $\beta_{at}^{\text{age:time}}$: 

\begin{equation}
  \pmb{\beta}_t^{\text{age:time}} \sim \text{N}(\pmb{\beta}_{t-1}^{\text{age:time}}, \sigma^2 \pmb{\Phi})
\end{equation}
where
\begin{equation}
  \pmb{\Phi} = \begin{bmatrix} 1 & \rho & \rho^2 & \dots & \rho^{T-1} \\
                                 \rho & 1 & \rho & \dots & \rho^{T-2} \\
				 \rho^2 & \rho & 1 & \dots & \rho^{T-3} \\
				 \vdots & \vdots & \vdots & \ddots & \vdots \\
				 \rho^{T-1} & \rho^{T-2} & \rho^{T-3} & \dots & 1 \end{bmatrix}
\end{equation}



